version: '3.8'
services:
  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test


  server:
    build: /server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_NAME=shareIt
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432



  gateway:
    build: /gateway
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090