# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  web:
    build: .
    ports:
      - "9090:9090"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - DB_NAME=shareIt
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=db
      - DB_PORT=5432
